'use client'

import React, { useState, useEffect } from 'react'
import { useField } from '@payloadcms/ui'
import {
  DndContext,
  closestCenter,
  KeyboardSensor,
  PointerSensor,
  useSensor,
  useSensors,
  DragEndEvent,
} from '@dnd-kit/core'
import {
  arrayMove,
  SortableContext,
  sortableKeyboardCoordinates,
  verticalListSortingStrategy,
  useSortable,
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'

// --- Sortable Table Row Component ---
function SortableItem({ id, promotion, onRemove }: { id: string, promotion: any, onRemove: (id: string) => void }) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
  } = useSortable({ id })

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    background: 'var(--theme-bg)',
    borderBottom: '1px solid var(--theme-elevation-100)',
    display: 'flex',
    alignItems: 'center',
    padding: '0.5rem 1rem',
  }

  return (
    <div ref={setNodeRef} style={style as React.CSSProperties}>
      <div style={{ width: '40px', cursor: 'grab' }} {...attributes} {...listeners}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--theme-elevation-400)' }}>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: '16px', height: '16px' }}>
            <circle cx="9" cy="12" r="1" />
            <circle cx="9" cy="5" r="1" />
            <circle cx="9" cy="19" r="1" />
            <circle cx="15" cy="12" r="1" />
            <circle cx="15" cy="5" r="1" />
            <circle cx="15" cy="19" r="1" />
          </svg>
        </div>
      </div>
      <div style={{ flex: 1, padding: '0.5rem', fontWeight: 500 }}>
        {promotion?.name || `ID: ${id}`}
      </div>
      <div style={{ width: '60px', textAlign: 'right' }}>
        <button 
          type="button" 
          onClick={() => onRemove(id)}
          style={{ 
            background: 'none', border: 'none', cursor: 'pointer', color: 'var(--theme-error-400)', padding: '0.25rem' 
          }}
          title="Удалить"
        >
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ width: '16px', height: '16px' }}>
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  )
}

// --- Main Field Component ---
export default function PromotionsListField({ path }: { path: string }) {
  const { value, setValue } = useField<string[]>({ path })
  const [promotions, setPromotions] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  // Fetch full promotion data based on IDs
  useEffect(() => {
    const fetchPromos = async () => {
      if (!value || value.length === 0) {
        setPromotions([])
        setLoading(false)
        return
      }

      setLoading(true)
      try {
        // We fetch from the local API endpoints generated by Payload
        const res = await fetch(`/api/promotions?where[id][in]=${value.join(',')}&limit=100`)
        const data = await res.json()
        
        if (data && data.docs) {
          // Sort fetched docs according to the `value` array order
          const sortedDocs = value.map(id => data.docs.find((doc: any) => String(doc.id) === String(id))).filter(Boolean)
          setPromotions(sortedDocs)
        }
      } catch (err) {
        console.error('Failed to fetch promotions for UI:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchPromos()
  }, [value])

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  )

  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event

    if (active.id !== over?.id) {
      const oldIndex = promotions.findIndex(item => String(item.id) === String(active.id))
      const newIndex = promotions.findIndex(item => String(item.id) === String(over?.id))
      
      const newItems = arrayMove(promotions, oldIndex, newIndex)
      
      // Update local state for immediate re-render of list
      setPromotions(newItems)
      
      // Update Payload form state outside of the functional updater
      setValue(newItems.map(item => item.id))
    }
  }

  const handleRemove = (idToRemove: string) => {
    const newValues = (value || []).filter(v => String(v) !== String(idToRemove))
    setValue(newValues)
  }

  if (loading) {
    return <div style={{ padding: '2rem 0', color: 'var(--theme-elevation-500)' }}>Загрузка списка акций...</div>
  }

  const isHomepage = path === 'homepagePromotions'
  const fieldLabel = isHomepage ? 'Акции на главной странице' : 'Акции в разделе'
  const fieldDescription = isHomepage
    ? 'Порядок акций на главной странице отеля. Перетащите строки чтобы изменить порядок. Добавить акцию — зайдите в Акции и поставьте галочку «На главной».'
    : 'Порядок акций в разделе «Акции» отеля. Перетащите строки чтобы изменить порядок. Добавить акцию — зайдите в Акции и поставьте галочку «В разделе».'

  return (
    <div style={{ marginBottom: '2rem' }}>
      <label style={{ 
        display: 'block', 
        marginBottom: '0.5rem', 
        fontWeight: 600, 
        color: 'var(--theme-elevation-800)',
        fontSize: '13px'
      }}>
        {fieldLabel}
      </label>
      
      <p style={{ fontSize: '13px', color: 'var(--theme-elevation-400)', marginBottom: '1rem', marginTop: 0 }}>
        {fieldDescription}
      </p>

      {promotions.length === 0 ? (
        <div style={{ 
          padding: '2rem', 
          border: '1px dashed var(--theme-elevation-200)', 
          borderRadius: '4px',
          textAlign: 'center',
          color: 'var(--theme-elevation-500)',
          fontSize: '14px'
        }}>
          Нет выбранных акций для этого отеля.
        </div>
      ) : (
        <div style={{ 
          border: '1px solid var(--theme-elevation-150)', 
          borderRadius: '4px',
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column'
        }}>
          <div style={{ 
            display: 'flex', 
            background: 'var(--theme-elevation-50)', 
            borderBottom: '1px solid var(--theme-elevation-150)',
            padding: '0.5rem 1rem' 
          }}>
            <div style={{ width: '40px' }}></div>
            <div style={{ flex: 1, fontSize: '12px', fontWeight: 600, color: 'var(--theme-elevation-500)', textTransform: 'uppercase' }}>Название</div>
            <div style={{ width: '60px' }}></div>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <DndContext 
              sensors={sensors}
              collisionDetection={closestCenter}
              onDragEnd={handleDragEnd}
            >
              <SortableContext 
                items={promotions.map(p => String(p.id))}
                strategy={verticalListSortingStrategy}
              >
                {promotions.map(promo => (
                  <SortableItem key={promo.id} id={String(promo.id)} promotion={promo} onRemove={handleRemove} />
                ))}
              </SortableContext>
            </DndContext>
          </div>
        </div>
      )}
    </div>
  )
}
